### ISSUE TITLE
Running into issues installing on Linux

### ISSUE THREAD

**Issue by rohjay** [octalmage/HotGifs#55]
Gave this a good ol' fashion:
```
npm install
npm start
```

No dice. Here's the output, but I'm guessing it's because I'm doing the wrong thing. Really, I just wanted you to know that I missed it enough to try on my new laptop running Ubuntu 18.04 =]

```
[00:14:31]rohjay@Sentinel::~/Downloads/Hotgifs/HotGifs-0.3.3>cat /home/rohjay/Downloads/Hotgifs/HotGifs-0.3.3/npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle HotGifs@0.3.3~prestart: HotGifs@0.3.3
6 silly lifecycle HotGifs@0.3.3~prestart: no script for prestart, continuing
7 info lifecycle HotGifs@0.3.3~start: HotGifs@0.3.3
8 verbose lifecycle HotGifs@0.3.3~start: unsafe-perm in lifecycle true
9 verbose lifecycle HotGifs@0.3.3~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/rohjay/Downloads/Hotgifs/HotGifs-0.3.3/node_modules/.bin:/Users/ryan.oeltjenbruns/bin:/usr/local/sbin:/usr/local/bin:/usr/local/mysql/bin:/home/rohjay/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle HotGifs@0.3.3~start: CWD: /home/rohjay/Downloads/Hotgifs/HotGifs-0.3.3
11 silly lifecycle HotGifs@0.3.3~start: Args: [ '-c', 'electron .' ]
12 info lifecycle HotGifs@0.3.3~start: Failed to exec start script
13 verbose stack Error: HotGifs@0.3.3 start: `electron .`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid HotGifs@0.3.3
15 verbose cwd /home/rohjay/Downloads/Hotgifs/HotGifs-0.3.3
16 error Linux 4.15.0-36-generic
17 error argv "/usr/bin/node" "/usr/bin/npm" "start"
18 error node v8.10.0
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error HotGifs@0.3.3 start: `electron .`
24 error spawn ENOENT
25 error Failed at the HotGifs@0.3.3 start script 'electron .'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the HotGifs package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     electron .
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs HotGifs
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls HotGifs
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```

I love you,
Ryan

**Comment by octalmage** [comment]
HEY MAN, I'LL CHECK IT OUT

**Comment by octalmage** [comment]
It might just be easier for me to start shipping Linux binaries.

**Comment by octalmage** [comment]
Ugh I forgot.

**Comment by octalmage** [comment]
I just got a Pixelbook which can run Linux apps, so I'll try running it on there!
